[workspace]
resolver = "3"
members = [".", "thirdparty/*"]

[package]
name = "ultravis"
version = "0.1.0"
edition = "2024"
description = "A quick and easy language and renderer for making music visualizers."
license = "MIT"
repository = "https://github.com/RedstoneWizard08/UltraVis"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
color-eyre = "0.6.5"
crossbeam = { version = "0.8.5", features = ["crossbeam-channel"] }
eyre = "0.6.14"
ffmpeg-next = { version = "9.0.0", features = ["static"] }
font-kit = { version = "0.14.3", features = ["freetype"] }
indicatif = { version = "0.18.6", features = ["rayon"] }
ndarray = "0.17.2"
ordered-float = "5.5.0"
peg = "0.8.6"
raqote = "0.8.5"
rayon = "1.12.0"
thiserror = "2.0.20"
video-rs = { path = "./thirdparty/video-rs", features = ["ndarray"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true

[profile.bench]
debug = true

[build-dependencies]
build-rs = "0.3.5"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/ultravis-{ target }"
pkg-fmt = "bin"
